# Autogenerated wrapper script for GAP_pkg_semigroups_jll for x86_64-unknown-freebsd
export semigroups

using GAP_jll
JLLWrappers.@generate_wrapper_header("GAP_pkg_semigroups")
JLLWrappers.@declare_file_product(semigroups)
function __init__()
    JLLWrappers.@generate_init_header(GAP_jll)
    JLLWrappers.@init_file_product(
        semigroups,
        "lib/gap/semigroups.so",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
